---
name: build

on:    # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - 'false'
  pull_request:
    branches-ignore:
      - 'false'

jobs:
  build:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest]
          python-version: ['3.9', '3.11']

      env:
        OS: ${{ matrix.os }}
        PYTHON: ${{ matrix.python-version }}

      steps:

        - uses: actions/checkout@v1

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e .[dev]

        - name: Test and generate coverage report on Linux
          run: |
            pytest --cov=./ --cov-report=xml
